# Terminal
alias ..='cd ..'
alias qq='exit'
alias c='clear'
alias r='reset'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Apt
alias sagi='sudo apt-get install'
alias sagr='sudo apt-get remove'
alias saga='sudo apt-get autoremove'
alias sagu='sudo apt-get update'
alias saar='sudo add-apt-repository'
alias sup='sudo apt-get update && sudo apt-get upgrade && sudo apt-get clean'
alias up='vim +BundleInstall! +BundleClean +qall && sudo apt-get update && sudo apt-get upgrade && sudo apt-get clean'

# Git
alias gcl='git clone'
alias gi='git init'
alias ga='git add'
alias ga.='git add .'
alias gau='git add -u'
alias gc='git commit'
alias gci='git commit -m'
alias gcia='git commit -am'
alias gciam='git commit --ammend -m'
alias gstf='git status'
alias gst='git status -s --branch'
alias gstis='git status --ignore-submodules'
alias glg='git log --graph --stat -p'
alias glgo='git log --oneline --graph'
alias gdf='git diff'
alias gdfc='git diff --cached'
alias gdfis='git diff --ignore-submodules'
alias gsma='git submodule add'
alias gsmi='git submodule init'
alias gsmu='git submodule update'
alias gsmui='git submodule update --init'
alias grtaog='git remote add origin'
alias gpsuogmt='git push -u origin master'
alias gplsub='git submodule foreach "git pull origin master"'
alias grm='git rm'
alias grmc='git rm --cached'

# Vim
alias v='vim'
alias gv='gvim'
alias vdf='vimdiff'
alias vup='vim +BundleInstall! +BundleClean +qall'

# Tmux
alias tmux='TERM=screen-256color-bce tmux'
alias t='TERM=screen-256color-bce tmux'

# Ack-grep
alias ack='ack-grep'
alias ackt='ack-grep --text'
alias ackp='ack-grep --python'
alias ackv='ack-grep --vim'

# Find
# find dir
alias findd='sudo find / -type d -name'
# find file
alias findf='sudo find / -type f -name'

# Extracting
alias tgz='tar xvzf'
alias tbz2='tar xvjf'

# du (file space usage)
alias du='du -hs * | sort -h'

# df (disk space usage)
alias df='df -h'
